version: '3'
services:
  prod:
    container_name: nextjs-prod
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'